---
title: "Exploration of group memberships"
author: Romain Frelat
date: today
format: 
  html:
    code-fold: false
    toc: true
execute:
  echo: true
  warning: false
---


The objective is to explore the relation among members of the [FRB-MTE-OFB projects](https://www.fondationbiodiversite.fr/la-frb-en-action/programmes-et-projets/impacts-sur-la-biodiversite-terrestre-dans-lanthropocene/). The raw data is not available on Github for privacy issue.

### Group membership

```{r}
devtools::load_all()
library(igraph)
library(visNetwork)

# load reference list
out_data <- here::here("data", "derived-data")
mem <- read.csv(file.path(out_data, "mte_members.csv"))

meta <- readxl::read_xlsx(
  here::here("data", "raw-data", "mte", "Projets_FRB-MTECT-OFB.xlsx")
)
# all(meta$Acronyme %in% mem$group)

table(mem$group, mem$function_in_group)

n_mem <- data.frame(table(mem$group))
n_mem$Type <- meta$Type[match(n_mem$Var1, meta$Acronyme)]
tapply(n_mem$Freq, n_mem$Type, summary)

nrow(mem) # 244 membership
```

```{r}
# dup <- duplicated(mem[, c("lastname", "firstname")])
# sum(duplicated(mem[, c("lastname", "firstname")])) # 21 ==
# sum(duplicated(mem$emails[!is.na(mem$emails)])) # 21

mem$name <- paste(mem$lastname, mem$firstname)
length(unique(mem$name)) # 223 members
```


### Group network

Based on shared members
```{r}
group_mem <- table(mem$group, mem$name)
member_overlap <- as.matrix(
  proxy::simil(group_mem, method = "russel", diag = TRUE, upper = TRUE) *
    ncol(group_mem)
)
diag(member_overlap) <- 0

netMEM <- igraph::graph_from_adjacency_matrix(
  member_overlap,
  mode = "undirected",
  weighted = TRUE
)

# plot(
#   netMEM,
#   layout = layout_with_mds(netMEM),
#   rescale = FALSE,
#   edge.width = E(netMEM)$weight
# )
# visNetwork::visIgraph(netMEM, randomSeed = 18)
```

```{r}
vcount(netMEM) # 24 nodes
ecount(netMEM) # 19 edges

# very low connectance: 0.06
edge_density(netMEM, loops = FALSE)

# as a matrix
# netmatrix <- as_adjacency_matrix(netMEM, sparse = F)
# heatmap(netmatrix, scale = "none")

modMEM <- cluster_walktrap(netMEM)
modularity(modMEM)
```

::: {.panel-tabset}
## modules
```{r}
modcol <- rainbow(max(membership(modMEM)))[membership(modMEM)]
V(netMEM)$color <- modcol
visNetwork::visIgraph(netMEM, randomSeed = 54)

# add a visualisation with year+jitter in x-axis
# mds in y axis based on distance network and year
```

## temporal
```{r}
# color by typexnod
vtyp <- as.factor(meta$Type[match(V(netMEM)$name, meta$Acronyme)])
typcol <- rainbow(nlevels(vtyp))[vtyp]
V(netMEM)$color <- typcol

# x-axis by year
vyr <- meta$Year[match(V(netMEM)$name, meta$Acronyme)]
xnod <- (vyr - min(vyr)) / (max(vyr) - min(vyr)) * 2 - 1

# take the first MDS dimension
ynod <- layout_with_mds(netMEM)[, 1]

# coordinates
coo <- cbind(jitter(xnod), ynod)

# plot(netMEM, layout = coo)
# laby <- sort(unique(vyr))
# seqy <- (laby - min(laby)) / (max(laby) - min(laby)) * 2 - 1
# axis(1, at = seqy, labels = laby)
visNetwork::visIgraph(
  netMEM,
  layout = 'layout.norm',
  layoutMatrix = coo,
  randomSeed = 54
)
```

:::


### Member network

Based on group membership

```{r}
pw <- c()
pw_pi <- c()
for (i in sort(unique(mem$group))) {
  ni <- mem$name[mem$group == i]
  pwi <- expand.grid(ni, ni)
  #remove identity / loop
  pwi <- pwi[pwi$Var1 != pwi$Var2, ]
  pw <- rbind(pw, pwi)

  # considering the central role of PI
  pi <- mem$name[
    mem$function_in_group %in% c("PI", "Post-doc") & mem$group == i
  ]
  pwi2 <- expand.grid(ni, pi)
  pwi2 <- pwi2[as.character(pwi2$Var1) != as.character(pwi2$Var2), ]
  pw_pi <- rbind(pw_pi, pwi2)
}

netRES <- igraph::graph_from_data_frame(pw, directed = FALSE)
# plot(
#   netRES,
#   layout = layout_with_mds(netRES),
#   vertex.label = NA
# )

netRES_PI <- igraph::graph_from_data_frame(pw_pi, directed = FALSE)
# plot(
#   netRES_PI,
#   layout = layout_with_mds(netRES_PI),
#   vertex.label = NA
# )
```

::: {.panel-tabset}
## all members
```{r}

vcount(netRES) # 223 nodes : members
ecount(netRES) # 2406 connections

# low connectance: 0.09
edge_density(netRES, loops = FALSE)

# netmatrix <- as_adjacency_matrix(netRES, sparse = FALSE)
# heatmap(netmatrix, scale = "none")

wtc <- cluster_walktrap(netRES)
modularity(wtc)

modcol <- rainbow(max(membership(wtc)))[membership(wtc)]
V(netRES)$color <- modcol
visNetwork::visIgraph(netRES)
```

## PI connected
```{r}

vcount(netRES_PI) # 223 nodes : members
ecount(netRES_PI) # 559 connections

# low connectance: 0.02
edge_density(netRES_PI, loops = FALSE)

wtc <- cluster_walktrap(netRES_PI)
modularity(wtc) #0.88

modcol <- rainbow(max(membership(wtc)))[membership(wtc)]
V(netRES_PI)$color <- modcol
visNetwork::visIgraph(netRES_PI)
```

:::